###
POST http://localhost:3010/servizio/jServizio
content-type: application/json

{

}

###

POST http://localhost:3010/servizio/jgLog
content-type: application/json

{

}

###

POST http://localhost:3010/servizio/jgFeedMore
content-type: application/json

{
 "logged":"u82371",
 "page": 0
}
###

POST http://localhost:3010/servizio/jgNewTreet
content-type: application/json

{
        "content": "I love you Baby",
        "author": "u000000000008523",
        "isComment": "",
        "isRetreet": ""
      }

###

POST http://localhost:3010/servizio/jgFeedTreet
content-type: application/json

{
        "idt":"t000000000000065",
        "page": 0
      }

###

POST http://localhost:3010/servizio/jgGetTreet
content-type: application/json

{
        "tid":"t000000000000065"
      }











