###
POST http://localhost:3000/servizio/jServizio
content-type: application/json

{

}

###

POST http://localhost:3000/servizio/jgLog
content-type: application/json

{

}

###

POST http://localhost:3000/servizio/jgFeed
content-type: application/json

{
 "logged":"u102727"
}












